services:
  mongodb:
    image: mongo:latest
    container_name: streamline-mdb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: streamline-sql
    ports:
      - "${SQL_PORT}:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: streamline-rmq
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env

volumes:
  mongodb_data:
  sqlserver_data:
  rabbitmq_data:
